//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motywator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motywator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o programie....
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lubie.
        /// </summary>
        public static string AppBarFavouriteCitation {
            get {
                return ResourceManager.GetString("AppBarFavouriteCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przewodnik....
        /// </summary>
        public static string AppBarGuide {
            get {
                return ResourceManager.GetString("AppBarGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie lubie.
        /// </summary>
        public static string AppBarNotFavouriteCitation {
            get {
                return ResourceManager.GetString("AppBarNotFavouriteCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to losuj cytat.
        /// </summary>
        public static string AppBarRandomCitation {
            get {
                return ResourceManager.GetString("AppBarRandomCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ustawienia....
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij.
        /// </summary>
        public static string AppBarShare {
            get {
                return ResourceManager.GetString("AppBarShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTYWUJ+.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulubiony.
        /// </summary>
        public static string ButtonFavorite {
            get {
                return ResourceManager.GetString("ButtonFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to losuj.
        /// </summary>
        public static string ButtonRandom {
            get {
                return ResourceManager.GetString("ButtonRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij.
        /// </summary>
        public static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkoda, że nie chcesz, ocenić Motywuj.
        ///
        ///Opowiedz nam o swoich wrażeniach lub zaproponować, co możemy zrobić aby program był jeszcze lepszy..
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie, dziękuję.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinie użytkownika Motywuj.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możemy zrobić to lepiej?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobileapp@aturex.pl.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyślij opinie.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o programie.
        /// </summary>
        public static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cytaty.
        /// </summary>
        public static string PageCitations {
            get {
                return ResourceManager.GetString("PageCitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulubione.
        /// </summary>
        public static string PageFavourite {
            get {
                return ResourceManager.GetString("PageFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przewodnik.
        /// </summary>
        public static string PageGuide {
            get {
                return ResourceManager.GetString("PageGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opcje.
        /// </summary>
        public static string PageOptions {
            get {
                return ResourceManager.GetString("PageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to losowy cytat.
        /// </summary>
        public static string PageRandomCitation {
            get {
                return ResourceManager.GetString("PageRandomCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ustawienia.
        /// </summary>
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij.
        /// </summary>
        public static string PageShare {
            get {
                return ResourceManager.GetString("PageShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcieli byśmy otrzymać od Ciebie 5 gwiazdek
        ///
        ///Twoje wsparcie doda nam otuchy przy pracy nad programem i sprawi że stanie się on lepszy!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widzimy, że często korzystasz z naszego programu!
        ///
        ///Może podarujesz nam 5 gwiazdek aby pokazać swoje uznanie?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie, dziękuję.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lubisz Motywuj?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chcę ocenić.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wszystkie wg. autora.
        /// </summary>
        public static string TextByAuthor {
            get {
                return ResourceManager.GetString("TextByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wszystkie wg. cytatu.
        /// </summary>
        public static string TextByCitation {
            get {
                return ResourceManager.GetString("TextByCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytat pochodzi z programu Motywuj dla Windows Phone.
        /// </summary>
        public static string TextCreatedBy {
            get {
                return ResourceManager.GetString("TextCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string TextEmail {
            get {
                return ResourceManager.GetString("TextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwielbiam Motywuj.
        /// </summary>
        public static string TextEmailSubiect {
            get {
                return ResourceManager.GetString("TextEmailSubiect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytat dodano do ulubionych.
        /// </summary>
        public static string TextFavouriteCietation {
            get {
                return ResourceManager.GetString("TextFavouriteCietation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przewodnik.
        /// </summary>
        public static string TextGuide {
            get {
                return ResourceManager.GetString("TextGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytat usunięto z ulubionych.
        /// </summary>
        public static string TextNotFavouriteCietation {
            get {
                return ResourceManager.GetString("TextNotFavouriteCietation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tylko ulubione.
        /// </summary>
        public static string TextOnlyFavorite {
            get {
                return ResourceManager.GetString("TextOnlyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oceń.
        /// </summary>
        public static string TextReview {
            get {
                return ResourceManager.GetString("TextReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij za pomocą e-mail.
        /// </summary>
        public static string TextShareEmail {
            get {
                return ResourceManager.GetString("TextShareEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij za pomocą sms.
        /// </summary>
        public static string TextShareSms {
            get {
                return ResourceManager.GetString("TextShareSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij status w sieci społecznościowej.
        /// </summary>
        public static string TextShareSocialNetwork {
            get {
                return ResourceManager.GetString("TextShareSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inne programy.
        /// </summary>
        public static string TextStore {
            get {
                return ResourceManager.GetString("TextStore", resourceCulture);
            }
        }
    }
}
