//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motywator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motywator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTYWUJ.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o programie.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dodaj.
        /// </summary>
        public static string ButtonAddCitation {
            get {
                return ResourceManager.GetString("ButtonAddCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anuluj.
        /// </summary>
        public static string ButtonAnuluj {
            get {
                return ResourceManager.GetString("ButtonAnuluj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulubiony.
        /// </summary>
        public static string ButtonFavorite {
            get {
                return ResourceManager.GetString("ButtonFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przewodnik.
        /// </summary>
        public static string ButtonGuide {
            get {
                return ResourceManager.GetString("ButtonGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie lubię.
        /// </summary>
        public static string ButtonNotFavorite {
            get {
                return ResourceManager.GetString("ButtonNotFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przypnij.
        /// </summary>
        public static string ButtonPin {
            get {
                return ResourceManager.GetString("ButtonPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to losuj.
        /// </summary>
        public static string ButtonRandom {
            get {
                return ResourceManager.GetString("ButtonRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to losuj.
        /// </summary>
        public static string ButtonRandomCitation {
            get {
                return ResourceManager.GetString("ButtonRandomCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ustawienia.
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij.
        /// </summary>
        public static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your feedback here]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkoda, że nie chcesz, ocenić Motywuj.
        ///
        ///Opowiedz nam o swoich wrażeniach lub zaproponować, co możemy zrobić aby program był jeszcze lepszy..
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie, dziękuję.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinie użytkownika Motywuj.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możemy zrobić to lepiej?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobileapp@aturex.pl.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyślij opinie.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O PROGRAMIE.
        /// </summary>
        public static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODAJ CYTAT.
        /// </summary>
        public static string PageAddCitation {
            get {
                return ResourceManager.GetString("PageAddCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DODAJ KAFELEK.
        /// </summary>
        public static string PageAddTile {
            get {
                return ResourceManager.GetString("PageAddTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cytaty.
        /// </summary>
        public static string PageCitations {
            get {
                return ResourceManager.GetString("PageCitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRZEWODNIK.
        /// </summary>
        public static string PageGuide {
            get {
                return ResourceManager.GetString("PageGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opcje.
        /// </summary>
        public static string PageOptions {
            get {
                return ResourceManager.GetString("PageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to losowy cytat.
        /// </summary>
        public static string PageRandomCitation {
            get {
                return ResourceManager.GetString("PageRandomCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USTAWIENIA.
        /// </summary>
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDOSTĘPNIJ.
        /// </summary>
        public static string PageShare {
            get {
                return ResourceManager.GetString("PageShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcieli byśmy otrzymać od Ciebie 5 gwiazdek
        ///
        ///Twoje wsparcie doda nam otuchy przy pracy nad programem i sprawi że stanie się on lepszy!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widzimy, że często korzystasz z naszego programu!
        ///
        ///Może podarujesz nam 5 gwiazdek aby pokazać swoje uznanie?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie, dziękuję.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lubisz Motywuj?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chcę ocenić.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autor.
        /// </summary>
        public static string TextAuthor {
            get {
                return ResourceManager.GetString("TextAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wszystkie wg. autora.
        /// </summary>
        public static string TextByAuthor {
            get {
                return ResourceManager.GetString("TextByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wszystkie wg. cytatu.
        /// </summary>
        public static string TextByCitation {
            get {
                return ResourceManager.GetString("TextByCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytat pochodzi z programu Motywuj dla Windows Phone.
        /// </summary>
        public static string TextCreatedBy {
            get {
                return ResourceManager.GetString("TextCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string TextEmail {
            get {
                return ResourceManager.GetString("TextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwielbiam Motywuj.
        /// </summary>
        public static string TextEmailSubiect {
            get {
                return ResourceManager.GetString("TextEmailSubiect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytat dodano do ulubionych.
        /// </summary>
        public static string TextFavouriteCietation {
            get {
                return ResourceManager.GetString("TextFavouriteCietation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to przewodnik.
        /// </summary>
        public static string TextGuide {
            get {
                return ResourceManager.GetString("TextGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Motywacja jest tym, co pozwala Ci zacząć. Nawyk jest tym, co pozwala Ci wytrwać&quot; - Jim Ryun.
        ///Nie masz ochoty rano wstać, brakuje Ci chęci do działania, marnujesz czas na zbędne zadania, zapominasz o celach... brakuje Ci motywacji!
        ///Program Motywuj zawiera zbiór cytatów motywacyjnych i o sukcesie. Poczytaj cytaty ludzi, którzy posiadają moc motywacji, aby pokonywania kolejne szczeble i wspinać się do góry.
        ///Wstań na nogi i osiągaj cele!.
        /// </summary>
        public static string TextInfo {
            get {
                return ResourceManager.GetString("TextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytat usunięto z ulubionych.
        /// </summary>
        public static string TextNotFavouriteCietation {
            get {
                return ResourceManager.GetString("TextNotFavouriteCietation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tylko ulubione.
        /// </summary>
        public static string TextOnlyFavorite {
            get {
                return ResourceManager.GetString("TextOnlyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuń reklamę.
        /// </summary>
        public static string TextRemoveAdd {
            get {
                return ResourceManager.GetString("TextRemoveAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oceń.
        /// </summary>
        public static string TextReview {
            get {
                return ResourceManager.GetString("TextReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij za pomocą e-mail.
        /// </summary>
        public static string TextShareEmail {
            get {
                return ResourceManager.GetString("TextShareEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij za pomocą sms.
        /// </summary>
        public static string TextShareSms {
            get {
                return ResourceManager.GetString("TextShareSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to udostępnij status w sieci społecznościowej.
        /// </summary>
        public static string TextShareSocialNetwork {
            get {
                return ResourceManager.GetString("TextShareSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inne programy.
        /// </summary>
        public static string TextStore {
            get {
                return ResourceManager.GetString("TextStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wersja.
        /// </summary>
        public static string TextVersion {
            get {
                return ResourceManager.GetString("TextVersion", resourceCulture);
            }
        }
    }
}
